version: "3.8"
name: project
services:
  db:
    build: db/ 
    ports:
      - "3306:3306"
    volumes:
    - /data/mysql/my.cnf:/etc/my.cnf
    - /data/mysql/conf.d/:/etc/mysql/conf.d/
    - /data/mysql/data/:/var/lib/mysql/
    networks:
    - projectnet
    env_file:
    - /opt/docker/project/db/.mysql_env
    expose:
    - "3306"
  end:
    build: end/
    ports:
    - "8080:8080"
    volumes:
    - /data/node/config.json:/app/config.json
    - /data/node/index.js:/app/index.js
    depends_on:
    - db
    networks:
    - projectnet
  front:
    build: front/
    ports: 
    - "80:80"
    volumes:
    - /data/nginx/conf.d/:/etc/nginx/conf.d/
    - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
    - /data/nginx/html/:/usr/share/nginx/html/
    networks:
    - projectnet
    depends_on:
    - end
networks:
  projectnet:
